### ISSUE TITLE
Database error when running test suite

### ISSUE THREAD

**Issue by Jrigada** [aave-dao/aave-helpers#202]
Hello! I am trying to run the test suite and I think I did everything in the README but I'm still getting 15 tests failing with the same error. 
`[FAIL. Reason: backend: failed while inspecting: Database error: failed to get account for 0x1f9090aaE28b8a3dCeaDf281B0F12828e676c326: (code: -32603, message: failed to forward request, data: None)] testListingsCustom() (gas: 0)`

I did install aave-cli and copy the .env and also forge and yarn is installed correctly. Is there anything I am missing? 

Thank you!

**Comment by sakulstra** [comment]
@Jrigada database error is related to your rpc not being able to fetch fresh data(usually public rpcs only support a certain amount of blocks in the past).
